setup-IaC:
    echo "Setup Infrastructure...!"
    rm -f {{justfile_directory()}}/inventory.ini
    ansible-playbook playbooks/main-iac.yaml
    ansible -i {{justfile_directory()}}/inventory.ini all -m ping

alias setup-Iac := setup-IaC
destroy:
    echo "Desroy the whole infrastructure...!"
    ansible-playbook playbooks/destroy-iac.yaml