ping-all:
    echo "Ping all instances inside inventory.ini"
    ansible -i inventory.ini all -m ping
nfs-server:
    echo "Setting up NFS Server...! 😀"
    ansible-playbook -i inventory.ini playbooks/nfs-server.yaml
nfs-client:
    echo "Setting up NFS Client...! 😀"
    ansible-playbook -i inventory.ini playbooks/nfs-client.yaml
install-docker:
    echo "Installing Docker on all servers...! 🐳"
    ansible-playbook -i inventory.ini playbooks/install-docker.yaml
test-nfs-sync:
    echo "Testing NFS folder synchronization...! 🔄"
    ansible-playbook -i inventory.ini playbooks/test-nfs-sync.yaml
run-spring-compose:
    echo "Run Spring Docker Compose...! 😀"
    echo "Test update this line to add for resolve conflict code!!!"
    ansible-playbook -i inventory.ini playbooks/run_spring_compose.yaml